# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20160801_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='slug',
            field=models.SlugField(default='', editable=False),
            preserve_default=False,
        ),
    ]
