# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20160804_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='menu.Menu'),
        ),
    ]
